/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialPythonSidebar: [
    { type: "autogenerated", dirName: "tutorial/python" },
  ],
  tutorialGoSidebar: [{ type: "autogenerated", dirName: "tutorial/golang" }],
  projectSidebar: [{ type: "autogenerated", dirName: "project" }],
};

module.exports = sidebars;
